//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartrigeAltstar.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langRU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CartrigeAltstar.Resources.langRU", typeof(langRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить картридж.
        /// </summary>
        internal static string AddCartigeModal {
            get {
                return ResourceManager.GetString("AddCartigeModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление подразделения.
        /// </summary>
        internal static string AddDepartmentModal {
            get {
                return ResourceManager.GetString("AddDepartmentModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый картридж добавлен.
        /// </summary>
        internal static string AddNewCartrigeMsgBox {
            get {
                return ResourceManager.GetString("AddNewCartrigeMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое подразделение добавленно.
        /// </summary>
        internal static string AddNewDepartmenMsgBox {
            get {
                return ResourceManager.GetString("AddNewDepartmenMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый принтер добавлен.
        /// </summary>
        internal static string AddNewPrinterMsgBox {
            get {
                return ResourceManager.GetString("AddNewPrinterMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить принтер.
        /// </summary>
        internal static string AddPrinterModal {
            get {
                return ResourceManager.GetString("AddPrinterModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикль.
        /// </summary>
        internal static string ArticleCartrige {
            get {
                return ResourceManager.GetString("ArticleCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string btnAddCartrige {
            get {
                return ResourceManager.GetString("btnAddCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string btnDellCartrige {
            get {
                return ResourceManager.GetString("btnDellCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Експортировать.
        /// </summary>
        internal static string btnExportExel {
            get {
                return ResourceManager.GetString("btnExportExel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        internal static string btnUpdateCartrige {
            get {
                return ResourceManager.GetString("btnUpdateCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картридж.
        /// </summary>
        internal static string Cartrige {
            get {
                return ResourceManager.GetString("Cartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картридж был удален.
        /// </summary>
        internal static string CartrigeWasRemoved {
            get {
                return ResourceManager.GetString("CartrigeWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оба поля должны быть заполненными.
        /// </summary>
        internal static string ChekFieldMessage {
            get {
                return ResourceManager.GetString("ChekFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картридж был обновлен.
        /// </summary>
        internal static string ChekFieldMessageUpdate {
            get {
                return ResourceManager.GetString("ChekFieldMessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение было обновленно.
        /// </summary>
        internal static string ChekFieldMessageUpdateDepartment {
            get {
                return ResourceManager.GetString("ChekFieldMessageUpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принтер удален.
        /// </summary>
        internal static string DelPrinterMsgBox {
            get {
                return ResourceManager.GetString("DelPrinterMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение было удалено.
        /// </summary>
        internal static string DepartmentWasRemoved {
            get {
                return ResourceManager.GetString("DepartmentWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес подразделения.
        /// </summary>
        internal static string lblAddressDepartment {
            get {
                return ResourceManager.GetString("lblAddressDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикль.
        /// </summary>
        internal static string lblArticle {
            get {
                return ResourceManager.GetString("lblArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата покупки.
        /// </summary>
        internal static string lblDatePurchase {
            get {
                return ResourceManager.GetString("lblDatePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель картриджа.
        /// </summary>
        internal static string lblModel {
            get {
                return ResourceManager.GetString("lblModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Названия подразделения.
        /// </summary>
        internal static string lblNameDepartment {
            get {
                return ResourceManager.GetString("lblNameDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список картриждей.
        /// </summary>
        internal static string ListOfCartrige {
            get {
                return ResourceManager.GetString("ListOfCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список подразделений.
        /// </summary>
        internal static string ListOfDepartment {
            get {
                return ResourceManager.GetString("ListOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список принтерoв.
        /// </summary>
        internal static string ListOfPrinrter {
            get {
                return ResourceManager.GetString("ListOfPrinrter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принтер был обновлен.
        /// </summary>
        internal static string MessageUpdatePrinter {
            get {
                return ResourceManager.GetString("MessageUpdatePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        internal static string ModelCartrige {
            get {
                return ResourceManager.GetString("ModelCartrige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель принтера.
        /// </summary>
        internal static string ModelPrinter {
            get {
                return ResourceManager.GetString("ModelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заметки.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список принтеров.
        /// </summary>
        internal static string printersList {
            get {
                return ResourceManager.GetString("printersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приемка.
        /// </summary>
        internal static string printReceptExel {
            get {
                return ResourceManager.GetString("printReceptExel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка.
        /// </summary>
        internal static string printSendingExel {
            get {
                return ResourceManager.GetString("printSendingExel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string purchase_date {
            get {
                return ResourceManager.GetString("purchase_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        internal static string Subivision {
            get {
                return ResourceManager.GetString("Subivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить картридж.
        /// </summary>
        internal static string UpdateCartigeModal {
            get {
                return ResourceManager.GetString("UpdateCartigeModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление подразделения.
        /// </summary>
        internal static string UpdateDepartmentModal {
            get {
                return ResourceManager.GetString("UpdateDepartmentModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить принтер.
        /// </summary>
        internal static string UpdatePrinterModal {
            get {
                return ResourceManager.GetString("UpdatePrinterModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принтер обновлен.
        /// </summary>
        internal static string UpdatePrinterMsgBox {
            get {
                return ResourceManager.GetString("UpdatePrinterMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись обновленна!!!!.
        /// </summary>
        internal static string WriteIsUpdated {
            get {
                return ResourceManager.GetString("WriteIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картридж на приемку записан.
        /// </summary>
        internal static string WriteSuccessCartigeIn {
            get {
                return ResourceManager.GetString("WriteSuccessCartigeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картридж на отправку записан.
        /// </summary>
        internal static string WriteSuccessCartigeOut {
            get {
                return ResourceManager.GetString("WriteSuccessCartigeOut", resourceCulture);
            }
        }
    }
}
